### ISSUE TITLE
Formatting with SubProperties

### ISSUE THREAD

**Issue by elvishfiend** [crozone/FormatWith#12]
I'm not sure how heavily inspired this is by the [James Newton-Kings'](http://james.newtonking.com/archive/2008/03/29/formatwith-2-0-string-formatting-with-named-variables) FormatWith, but that would allow you to specify a SubProperty (the same as you can with Interpolated Strings).

e.g.

    var foo = new { Property = new { SubProperty = "SubProperty" }};
    var bar = "{Property.SubProperty}".FormatWith(foo);
    var baz = $"{foo.Property.SubProperty}";

    // bar = "SubProperty"
    // baz = "SubProperty"

It doesn't look like it would be too hard to implement, just requires splitting the Key to get the Members.

**Comment by crozone** [comment]
Thanks for the PR! I'll test this and try to get it merged soon and then pushed up to nuget.

Believe it or not I'd actually considered implementing property traversal in the past, but avoided it because of indexers, and methods. At the time I thought that allowing property traversal would imply some level of language parsing which might suggest that you could also do something like `$"{foo.Property.SubProperty[0].Get(5)}"`. Implementing indexer parsing and reflection isn't too bad, but the complexity starts to balloon with methods which is why I dropped it. At that stage it's almost easier to call into Roslyn to do a dynamic codegen (which is actually what some of the older string interpolation libraries did!)

However looking at this again, I think allowing simple property navigation is fine. Just as along as the end user understands the limitations.
